--- #YAML:1.0
name:               github_creator
version:            0.15
abstract:           Create a Github repository for your Perl module
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::IniFiles:     0
    File::Find::Closures:  0
    Log::Log4perl:        0
    Test::More:           0
    Test::Output:         0
    WWW::Mechanize:       0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
