--- #YAML:1.0
name:                github_creator
version:             0.13
abstract:            Create a Github repository for your Perl module
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Config::IniFiles:              0
    File::Find::Closures:          0
    Log::Log4perl:                 0
    Test::More:                    0
    Test::Output:                  0
    WWW::Mechanize:                0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
